import { jsPDF } from 'jspdf';
import { Result, Query } from '../types';

export function exportAnalysisPDF(query: Query, result: Result): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header Banner
  doc.setFillColor(10, 36, 99); // #0A2463
  doc.rect(0, 0, pageWidth, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SatQuery AI - Intelligence Briefing', 14, 18);

  // Metadata strip
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toUTCString()} | Report ID: ${result.id}`, 14, 36);

  // Natural Language Query Block
  doc.setFillColor(248, 249, 250);
  doc.roundedRect(14, 42, pageWidth - 28, 26, 2, 2, 'F');
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Submitted Natural Language Query:', 18, 50);
  doc.setFont('helvetica', 'italic');
  doc.text(`"${query.text}"`, 18, 58, { maxWidth: pageWidth - 36 });

  // Synthesized AI Findings
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(10, 36, 99);
  doc.text('Multimodal Analytical Response', 14, 80);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  doc.text(result.text, 14, 88, { maxWidth: pageWidth - 28, lineHeightFactor: 1.4 });

  // Execution Summary Metrics
  const summaryTop = 125;
  doc.setFillColor(241, 245, 249);
  doc.rect(14, summaryTop, pageWidth - 28, 30, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text('Confidence Score:', 20, summaryTop + 10);
  doc.text('Backbone Model:', 20, summaryTop + 18);
  doc.text('Execution Latency:', 20, summaryTop + 25);

  doc.setFont('helvetica', 'normal');
  doc.text(`${(result.confidence * 100).toFixed(1)}% (High Veracity)`, 70, summaryTop + 10);
  doc.text(result.metadata.modelUsed, 70, summaryTop + 18);
  doc.text(`${result.metadata.executionTime} ms`, 70, summaryTop + 25);

  // Detected Spatial Objects List
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(10, 36, 99);
  doc.text('Grounding Detections & Coordinates', 14, 170);

  let yOffset = 180;
  result.visualEvidence.annotations.forEach((box, index) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    const coordStr = `Bounding [Lat: ${box.coordinates[0]}, Lng: ${box.coordinates[1]} to ${box.coordinates[2]}, ${box.coordinates[3]}]`;
    doc.text(`${index + 1}. ${box.label} (${(box.confidence * 100).toFixed(0)}%) - ${coordStr}`, 16, yOffset);
    yOffset += 8;
  });

  // Footer stamp
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Confidential - Generated by SatQuery AI Autonomous Satellite Analysis System', 14, 285);

  doc.save(`SatQuery_Report_${result.id}.pdf`);
}